name: Docker Image Test Build

on:
  pull_request:
    branches:
      ignore:
        - master

jobs:

  build:
 
    runs-on: ubuntu-18.04
 
    steps:
    - name: Checkout GitHub Repository
      uses: actions/checkout@v1
    - name: Build the Docker image
      run: |
        docker build --file docker/Dockerfile -t quay.io/vanessa/encode-demo-workflow .
